### ISSUE TITLE
After running the tool, still have qualsys issue

### ISSUE THREAD

**Issue by Lewiscowles1986** [zakjan/cert-chain-resolver#11]
So I was receiving this error message, but it still persists after using this tool.

"This server's certificate chain is incomplete. Grade capped to B."

```
sudo ./cert-chain-resolver/src/cert-chain-resolver.sh -o domain.bundle.pem domain.crt
```

I'm wondering if the problem is that the CA certs contain an anchor as after running this tool I've gone from having a single extra-download with one path, to two paths, one with one extra-download, the other with two extra downloads... I've never encountered this issue before, normally I can just cat the CA files and I get an A+...

CentOS7 Apache2+mod_ssl

TIA

**Comment by zakjan** [comment]
Hi, can you attach the original certificate, so I can debug it?

**Comment by Lewiscowles1986** [comment]
Sorry, but that would be problematic. I solved the problem by switching to my regular SSL certificate provider, and got a refund on the cert in question

**Comment by zakjan** [comment]
That's no problem, even if the certificate is revoked and not used on any site, I can use it for debugging. Just send me the domain.crt file, without private key. If you don't want to publish it here, you can find the email on my personal website.
