### ISSUE TITLE
cert-chain-resolver seems to segfault on OS X 10.13 (High Sierra)

### ISSUE THREAD

**Issue by lucasRolff** [zakjan/cert-chain-resolver#19]
I tried to use the darwin build for OS X 10.13 (High Sierra), and I saw that it gives a `segmentation fault: 11` whenever I try to run it.

However if I manually build the binary on the OS, it seems to work perfectly.

**Comment by zakjan** [comment]
I rebuilt it and released, looks like it fixed it.

**Comment by zakjan** [comment]
I din't know what was wrong, but rebuild fixed it.

**Comment by zakjan** [comment]
I don't know what was wrong, but rebuild fixed it.
