### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by MuruganChandrasekar** [zakjan/cert-chain-resolver#22]
`root@server:/certs/cert-chain-resolver# glide install`
[WARN]  The name listed in the config file (github.com/zakjan/cert-chain-resolver) does not match the current location (.)
[INFO]  Downloading dependencies. Please wait...
[INFO]  --> Fetching github.com/urfave/cli
[INFO]  --> Fetching github.com/stretchr/testify
[INFO]  --> Fetching github.com/fullsailor/pkcs7
[INFO]  Setting references.
[INFO]  --> Setting version for github.com/fullsailor/pkcs7 to 2585af45975b11f1d7502bb6c01556c29efb54ce.
[INFO]  --> Setting version for github.com/stretchr/testify to f390dcf405f7b83c997eac1b06768bb9f44dec18.
[INFO]  --> Setting version for github.com/urfave/cli to 01a33823596e7cffafa9e037acdd2441dc0eb03f.
[INFO]  Exporting resolved dependencies...
[INFO]  --> Exporting github.com/fullsailor/pkcs7
[INFO]  --> Exporting github.com/stretchr/testify
[INFO]  --> Exporting github.com/urfave/cli
[INFO]  Replacing existing vendor dependencies

`root@server:/certs/cert-chain-resolver# go build`
main.go:5:2: cannot find package "github.com/urfave/cli" in any of:
        /usr/local/go/src/github.com/urfave/cli (from $GOROOT)
        /root/work/src/github.com/urfave/cli (from $GOPATH)
main.go:6:2: cannot find package "github.com/zakjan/cert-chain-resolver/certUtil" in any of:
        /usr/local/go/src/github.com/zakjan/cert-chain-resolver/certUtil (from $GOROOT)
        /root/work/src/github.com/zakjan/cert-chain-resolver/certUtil (from $GOPATH)

please help..

**Comment by zakjan** [comment]
Hi, try cloning the repo into your $GOPATH, in that time with Go 1.6 it was necessary, it's documented at https://github.com/zakjan/cert-chain-resolver#build and linked Go issue https://github.com/golang/go/issues/12511

As an alternative, does downloading a pre-built release from https://github.com/zakjan/cert-chain-resolver/releases work for you?

Also, with the latest Go, the best practices might have changed, I welcome any suggestions to update the build process and vendoring dependencies.

**Comment by zakjan** [comment]
Fixed in #24
